# NUMPY #

NumPy is the fundamental package for scientific computing with Python. It stands for 
“Numerical Python.” It supports: 

• N-dimensional array object

• Broadcasting functions

• Tools for integrating C/C++ and Fortran code

• Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as a multi-dimensional container to store generic data. Arbitrary data types can also be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy’s main object is the homogeneous multidimensional array. An array is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers and represented by a single variable. NumPy’s array class is called ndarray. It is also known by the alias array.

In NumPy arrays, the individual data items are called elements. All elements of an array 
should be of the same type. Arrays can be made up of any number of dimensions. In NumPy, dimensions are called axes. Each dimension of an array has a length which is the total number of elements in that direction. The size of an array is the total number of elements contained in an array in all the dimension. The size of NumPy arrays are fixed; once created it cannot be changed again.

# To create Numpy array using list / tuple #


In [10]:
import numpy as np
ar1 = np.array([1,20,3,40,5,60])   #np.array()

In [11]:
ar1

array([ 1, 20,  3, 40,  5, 60])

In [12]:
# Get the datatype of individual element
ar1.dtype

dtype('int32')

In [13]:
type(ar1)

numpy.ndarray

In [14]:
no=10
type(no)

int

In [15]:
ar1=np.array([10,20,30,40,50],'int16')

In [10]:
# Set the datatype of individual element
ar1.dtype

dtype('int16')

In [16]:
# To display the size( no. elements) of the numpy array
ar1.size

5

In [17]:
# To display the shape of the numpy array
ar1.shape           

(5,)

In [18]:
x=np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,0],
        [1,9,0]
    ]
)

In [24]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

In [25]:
x.shape

(4, 3)

In [3]:
y=np.array([[[10,]]])

In [4]:
# To display the no. of dimentions of the numpy array
y.ndim

3

## ar1    
0    1    2     3    4     5
-6  -5   -4   -3    -2    -1

In [18]:
ar1[2] = 100

In [19]:
ar1

array([ 10,  20, 100,  40,  50], dtype=int16)

In [20]:
x[3,1]

9

In [21]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

In [22]:
#create numpy array using tuple
y = np.array((2,5)) 

In [23]:
y.size

2

In [27]:
#create numpy array filled with zero
x_zero=np.zeros((4,5))

In [28]:
x_zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
#create numpy array filled with zero
x_one=np.ones((7,5))

In [30]:
x_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
x_one.shape

(7, 5)

In [32]:
x_one.size

35

In [33]:
ar1

array([ 10,  20, 100,  40,  50], dtype=int16)

In [34]:
x_one.ndim

2

ar1.ndim

In [35]:
# To create numpy array of 0-N values
z=np.arange(15).reshape(3,5)
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
z=np.linspace(1,10,5)  # np.linspce(start,stop,No.of elements) 
z

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [5]:
# To create identity matrix
g=np.identity(5)  
g

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

In [41]:
# To transpose of matrix
x.T   # or x.transpose()

array([[1, 4, 7, 1],
       [2, 5, 8, 9],
       [3, 6, 0, 0]])

In [42]:
z=np.arange(150)

In [44]:
z.shape

(150,)

In [45]:
# To use reshape 
y=z.reshape(3,50)

In [46]:
y

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]])

In [47]:
# Flatten the array i.e. convert to 1-D array
z=z.ravel()

In [48]:
z

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149])

In [49]:
z.ndim

1

In [50]:
z.shape

(150,)

In [51]:
# To create 1-D array with random 'n' values
x_rnd=np.random.rand(10)

In [52]:
x_rnd

array([0.64250661, 0.79227474, 0.61222122, 0.38953237, 0.36633315,
       0.3764887 , 0.25873893, 0.44837152, 0.34749834, 0.39514531])

In [53]:
# To create 2-D array with random  values
x_rnd=np.random.rand(5,3)

In [54]:
x_rnd

array([[0.58231006, 0.20144504, 0.62062029],
       [0.37132718, 0.92547565, 0.40999554],
       [0.32050979, 0.97950131, 0.41485327],
       [0.66474026, 0.79863422, 0.23574865],
       [0.1699211 , 0.53526174, 0.55449103]])

In [55]:
#creates an array of specified shape and fills it with random values as per standard normal distribution. 
x_rnd=np.random.randn(15)

In [56]:
x_rnd

array([ 7.86040954e-01, -8.65644485e-01, -2.20851955e-01,  1.74219950e+00,
        9.07748945e-01, -1.76295577e-01, -1.36668800e-04, -8.49053090e-01,
        3.17068928e-01,  6.11605037e-01, -1.18938078e+00, -1.32601452e+00,
       -3.77877048e-01,  4.65336281e-02, -1.78034077e+00])

In [57]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

In [58]:
ar1

array([ 10,  20, 100,  40,  50], dtype=int16)

In [61]:
#creates an array of specified shape (5,2) and fills it with random values between 0-100. 
x_rnd=np.random.randint(0,100,(5,2))   # np.random.seed(10) 

In [62]:
x_rnd

array([[26, 28],
       [35, 36],
       [11, 78],
       [47, 88],
       [97, 19]])

In [63]:
x_rnd.shape

(5, 2)

In [64]:
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

Methods


In [65]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0],
       [1, 9, 0]])

In [66]:
x.min()

0

In [67]:
x.max()

9

In [68]:
x.sum()

46

In [69]:
import numpy as np

In [6]:
x=np.array([[10,2,3],[4,25,6],[0,8,0]])
x

array([[10,  2,  3],
       [ 4, 25,  6],
       [ 0,  8,  0]])

In [73]:
#Returns the indices of the maximum values along an axis.
x.argmax()

4

In [74]:
x.min()

0

In [75]:
#Returns the indices of the minimum values along an axis.
x.argmin()

6

In [77]:
x

array([[10,  2,  3],
       [ 4, 25,  6],
       [ 0,  8,  0]])

In [157]:
#Returns the columnwise maximum values axis.
x.max(axis=0)

array([10, 25,  6])

In [78]:
#Returns the columnwise maximum values axis.
x.max(axis=1)

array([10, 25,  8])

In [79]:
# Maximum of the flattened array
np.amax(x)

25

In [80]:
#Returns the columnwise sum -first axis.
x.sum(axis=0)   # or x.sum(0)

array([14, 35,  9])

In [82]:
#Returns the rowwise sum -second axis.
x.sum(0)

array([14, 35,  9])

In [83]:
#Returns the  sum along the -last axis.
x.sum(-1)

array([15, 35,  8])

# Arithmetic operations

In [27]:
# addition of two lists
L1=[1,2,3,4,5]
L2=[10,20,30,40]
L1+L2   # concatinate

[1, 2, 3, 4, 5, 10, 20, 30, 40]

In [29]:
L2*2    # repeates the list elements

[10, 20, 30, 40, 10, 20, 30, 40]

In [30]:
# Operations with 1-D numpy array
Nr1=np.array([4,2,10])
Nr2=np.array([3,4,5])

In [89]:
Nr1+Nr2

array([ 7,  6, 15])

In [90]:
# Operations with 2-D numpy array
m1=np.array([[1,2,3],[3,4,5]])
m2=np.array([[4,2,1],[2,1,4]])

In [91]:
m1

array([[1, 2, 3],
       [3, 4, 5]])

In [92]:
m2

array([[4, 2, 1],
       [2, 1, 4]])

In [93]:
m1*m2

array([[ 4,  4,  3],
       [ 6,  4, 20]])

In [94]:
m1/m2

array([[0.25, 1.  , 3.  ],
       [1.5 , 4.  , 1.25]])

In [95]:
m1-m2

array([[-3,  0,  2],
       [ 1,  3,  1]])

In [96]:
m1+m2

array([[5, 4, 4],
       [5, 5, 9]])

In [97]:
ar1

array([ 10,  20, 100,  40,  50], dtype=int16)

In [4]:
ar1=np.array([30,40,20,35,15,100])

In [5]:
# sort the array
np.sort(ar1)

array([ 15,  20,  30,  35,  40, 100])

In [6]:
ar1

array([ 30,  40,  20,  35,  15, 100])

In [5]:
#change the specific element ( indexing)
ar1[0] = 0
ar1[4] = 0

In [8]:
ar1

array([  0,  40,  20,  35,   0, 100])

In [9]:
#count nonzero elements
np.count_nonzero(ar1)

4

In [186]:
np.nonzero(ar1)

(array([1, 2, 3], dtype=int64),)

In [103]:
ar1

array([ 30,  40,  20,  35,  15, 100])

In [102]:
np.where(ar1>30)

(array([1, 3, 5], dtype=int64),)

In [104]:
py_ar=[0,4,10,30,10]
np_ar=np.array(py_ar)

In [105]:
type(py_ar)

list

In [106]:
type(np_ar)

numpy.ndarray

In [108]:
import sys
sys.getsizeof(1)*len(py_ar)

140

In [109]:
sys.getsizeof(np_ar.itemsize*np_ar.size)

28

In [110]:
#otal bytes consumed by the elements of the array.
np_ar.nbytes

20

# slicing


In [10]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
t1 = x[2:-2]
t1

array([2, 3, 4, 5, 6, 7])

In [17]:
type(t1)

numpy.ndarray

#Advance Indexing 

In [6]:
x = np.array([[1, 2], [3, 4], [5, 6],[7,8]])

In [7]:
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
x[[r1,r2,r3,rn],[c1,c2,c3,cn]]     # x[r1,c1], x[r2,c2], x[rn,cn]

NameError: name 'r1' is not defined

In [ ]:
x[[0, 1, 2,3], [0, 1, 0,1]]   # returns ( 0,0 ; 1,1 ; 2,0)

In [ ]:
x = np.array([[0, 1], [1, 1], [2, 2],[5,3]])
rowsum = x.sum(-1)
x[rowsum <= 4, :]

In [ ]:
x        #rowsum 1- 1   2->2   3->4

In [35]:
import pandas as pd
data= {
    "Name":["AA","BB","CC"],
    "Age":[11,22,33]
}
ss = pd.DataFrame(data)
ss
ss.to_csv("UUU.csv")
print("Done")
ss.to_csv("VV.csv", index=False)
print("Done@")

Done
Done@


In [44]:
a = pd.read_csv("VV.csv")
a.tail(2)

Name  Age
1   BB   22
2   CC   33

In [ ]:
x.sum(0)  # i sequivalent to x.sum(axis=0)

In [ ]:
x.sum(-1)  # i sequivalent to x.sum(axis=1)

In [100]:
x.sum(axis=0)

array([14, 35,  9])