In [1]:
import numpy as np
import sys

In [2]:
d2 = np.array([ [1,2,3,4,5] , [6,7,8,9,0] ])
print(d2)
print("Type of elements: ",d2.dtype)
print("size of each element: ",d2.itemsize)
print("shape of d2: ",d2.shape)
print("dimension of d2: ",d2.ndim )

[[1 2 3 4 5]
 [6 7 8 9 0]]
Type of elements:  int32
size of each element:  4
shape of d2:  (2, 5)
dimension of d2:  2


In [6]:
c = np.array([ [1,2,3,4,5,6,7],[8,9,10,11,12,13,14] ])
print(c)
print("Shape : ",c.shape)
print("Dimension:  ",c.ndim)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
Shape :  (2, 7)
Dimension:   2


In [7]:
#get specific element [r, c]
print(c[0,-2])
print(c[1,-2])

6
13


In [63]:
# get a specific row
print(c[0,:])
print(c[1,:])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [66]:
# get a specific column
print(c[:, 2])
print(c[:, 4])

[ 3 10]
[ 5 12]


In [77]:
#get specific indexes   [start : end : stepsize]
print("First Row: ",c[0, 1:-1:2])     
print("Second Row:",c[1, -6:-1:2])   

First Row:  [2 4 6]
Second Row: [ 9 11 13]


In [79]:
# changing value  by index
c[1,5] = 100  
print(c)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 100  14]]


In [83]:
# changing value column wise
c[:, 2] = [444, 555]
print(c)

[[  1   2 444   4   5   6   7]
 [  8   9 555  11  12 100  14]]


In [ ]:
# 3D #-dimensional 

In [95]:
d = np.array([ [[1,2], [3,4]] , [[5,6],[7,8]]  ])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [104]:
#get specific element (Work outside in)
d[0,1,1]

4

In [113]:
#replace   
d[:,1,:] = [[9,9],[8,8]]        # 1 = per array 1 index 
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [197]:
print("0's matrix")
print(np.zeros([2,3]))
print()

print("1's matrix")
print(np.ones([5]))
print()

print("1's matrix with dimension")
print(np.ones([2,3]))

0's matrix
[[0. 0. 0.]
 [0. 0. 0.]]

1's matrix
[1. 1. 1. 1. 1.]

1's matrix with dimension
[[1. 1. 1.]
 [1. 1. 1.]]


In [196]:
# for any other numberss
np.full((2,3),0)

array([[0, 0, 0],
       [0, 0, 0]])

In [128]:
np.full((2,3),33)

array([[33, 33, 33],
       [33, 33, 33]])

In [130]:
# any other no full_like
np.full_like(a.shape,4)

array([4])

In [198]:
#Random function
np.random.rand(4,2)

array([[0.90817247, 0.94200981],
       [0.18505025, 0.35467079],
       [0.50742177, 0.20546034],
       [0.71543022, 0.74451068]])

In [9]:
#random Integer value
np.random.randint(10, size=(3,4))

array([[0, 8, 4, 6],
       [2, 2, 4, 4],
       [0, 2, 9, 0]])

In [146]:
# Start to end (-9, 10)
np.random.randint(-9, 10, size=(3,4))

array([[ 2, -5, -1, -8],
       [ 0, -3,  6, -2],
       [-9,  6, -2,  5]])

In [149]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
# repeatd numbers
arr = np.array([1,2,3])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [167]:
# copying array
a = np.array([1,2,3,4])
b = a.copy()
b[1] = 100
print("B:",b)
print("A:",a)

B: [  1 100   3   4]
A: [1 2 3 4]


In [176]:
#Arithmatic opearations with each row element
print("Addition: ",a+2)
print("Subtration: ",a-2)
print("Multiplication; ",a*2)
print("Division: ",a//2)
print("Power 2: ",a**2)

Addition:  [3 4 5 6]
Subtration:  [-1  0  1  2]
Multiplication;  [2 4 6 8]
Division:  [0 1 1 2]
Power 2:  [ 1  4  9 16]


In [184]:
# Geometrical values of each element
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [186]:
# Statistic function
S = ([ [1,2,3],[4,5,6]  ])
print("Sum: ",np.sum(S))
print("min: ",np.min(S))
print("max: ",np.max(S))

Sum:  21
min:  1
max:  6


In [11]:
#reshape the array
before = np.array([ [1,2,3,4] ,[5,6,7,8] ])
print(before)
print()
after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
before = np.array([ [1,2,3,4] ,[5,6,7,8] ])
print(before)
print()
after = before.reshape(4,2)
print(after)

In [211]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)

[[23. 23. 26. 41. 12. 41.  2. 24. 34. 26.  2.]
 [21. 43. 22. 43. 41.  7. 28. 32.  9. 33. 38.]
 [ 4. 32.  9. 46. 31. 35. 42.  4. 20. 28. 33.]]


In [239]:
print(filedata[filedata>40])
print()
print(filedata>40)
print()
(filedata>40) & (filedata<45)

[41. 41. 43. 43. 41. 46. 42.]

[[False False False  True False  True False False False False False]
 [False  True False  True  True False False False False False False]
 [False False False  True False False  True False False False False]]



array([[False, False, False,  True, False,  True, False, False, False,
        False, False],
       [False,  True, False,  True,  True, False, False, False, False,
        False, False],
       [False, False, False, False, False, False,  True, False, False,
        False, False]])