In [ ]:

Write a pythan program to perform following operations. on MongoDB
Database. [5]
i) Create collection “EMP” with fields:
Emp-name, Emp- mobile, Emp, sal, Age
ii) Insert 5 documents.
iii) Find the employees getting salary between 5000 to 10000.
iv) Update mobile number for the employee named as “Riddhi”
v) Display all employees in the order of “Age”

In [4]:
!pip install pymongo


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
#i
from pymongo import *
client = MongoClient(host="mongodb://localhost:27017")
collection = client["yash"]["EMP"]

# v
collection.create_index("Age")

'Age_1'

In [7]:
#ii
query = (
    {"Name":"AAA",     "Mobile":123 ,  "Salary":5000,  "ID":1, "Age":21},
    {"Name":"BBB",     "Mobile":124 ,  "Salary":6000,  "ID":2, "Age":22},
    {"Name":"Siddhi",  "Mobile":125 ,  "Salary":7000,  "ID":3, "Age":23},
    {"Name":"DDD" ,    "Mobile":126 ,  "Salary":8000,  "ID":4, "Age":25},
    {"Name":"EEE",     "Mobile":127 ,  "Salary":11000, "ID":5, "Age":25}
)

insert = collection.insert_many(query)

for record in collection.find():
    print(record)
    

{'_id': ObjectId('64b2decc83c69a5670db3713'), 'Name': 'AAA', 'Mobile': 123, 'Salary': 5000, 'ID': 1, 'Age': 21}
{'_id': ObjectId('64b2decc83c69a5670db3714'), 'Name': 'BBB', 'Mobile': 124, 'Salary': 6000, 'ID': 2, 'Age': 22}
{'_id': ObjectId('64b2decc83c69a5670db3715'), 'Name': 'Siddhi', 'Mobile': 125, 'Salary': 7000, 'ID': 3, 'Age': 23}
{'_id': ObjectId('64b2decc83c69a5670db3716'), 'Name': 'DDD', 'Mobile': 126, 'Salary': 8000, 'ID': 4, 'Age': 25}
{'_id': ObjectId('64b2decc83c69a5670db3717'), 'Name': 'EEE', 'Mobile': 127, 'Salary': 11000, 'ID': 5, 'Age': 25}


In [12]:

#iii
query = {"Salary":{"$gte":5000, "$lte":10000}}
                  
for record in collection.find(query):
    print(record)

{'_id': ObjectId('64b2decc83c69a5670db3713'), 'Name': 'AAA', 'Mobile': 123, 'Salary': 5000, 'ID': 1, 'Age': 21}
{'_id': ObjectId('64b2decc83c69a5670db3714'), 'Name': 'BBB', 'Mobile': 124, 'Salary': 6000, 'ID': 2, 'Age': 22}
{'_id': ObjectId('64b2decc83c69a5670db3715'), 'Name': 'Siddhi', 'Mobile': 125, 'Salary': 7000, 'ID': 3, 'Age': 23}
{'_id': ObjectId('64b2decc83c69a5670db3716'), 'Name': 'DDD', 'Mobile': 126, 'Salary': 8000, 'ID': 4, 'Age': 25}


In [18]:
#iv
query = {"$set":{"Mobile":999}}

record = collection.update_one({"Name":"Siddhi"},query)
for record in collection.find():
    print(record)

{'_id': ObjectId('64b2decc83c69a5670db3713'), 'Name': 'AAA', 'Mobile': 123, 'Salary': 5000, 'ID': 1, 'Age': 21}
{'_id': ObjectId('64b2decc83c69a5670db3714'), 'Name': 'BBB', 'Mobile': 124, 'Salary': 6000, 'ID': 2, 'Age': 22}
{'_id': ObjectId('64b2decc83c69a5670db3715'), 'Name': 'Siddhi', 'Mobile': 999, 'Salary': 7000, 'ID': 3, 'Age': 23}
{'_id': ObjectId('64b2decc83c69a5670db3716'), 'Name': 'DDD', 'Mobile': 126, 'Salary': 8000, 'ID': 4, 'Age': 25}
{'_id': ObjectId('64b2decc83c69a5670db3717'), 'Name': 'EEE', 'Mobile': 127, 'Salary': 11000, 'ID': 5, 'Age': 25}


In [18]:
import numpy as np
array_5x5 = np.random.randint(1,100, size=(5,5))
top_left_2x2 = array_5x5[:2, 3:]

print("Original 5x5 array:")
print(array_5x5)

print("\nTop-left 2x2 array:")
print(top_left_2x2)


Original 5x5 array:
[[ 3 73 90 91 53]
 [11 90  6 50 63]
 [56 90 49 64 74]
 [98 16 61 40 63]
 [65 49 90 20  6]]

Top-left 2x2 array:
[[91 53]
 [50 63]]
